name: All-U-Want
version: 1.0.0-SNAPSHOT-@apiversion@
description: All-U-Want
authors: [ DartPower, mister_person ]
website: https://github.com/dptmc/All-U-Want
main: io.dpteam.AllUWant.Main
depend: [ProtocolLib]
permissions:
    alluwant.*:
        default: false
        children:
            alluwant.item.creative: true
            alluwant.item.survival: true
            alluwant.block.creative: true
            alluwant.block.survival: true
            alluwant.entity.creative: true
            alluwant.entity.survival: true
    alluwant.item.creative:
        default: false
    alluwant.item.survival:
        default: false
    alluwant.block.creative:
        default: false
    alluwant.block.survival:
        default: false
    alluwant.entity.creative:
        default: false
    alluwant.entity.survival:
        default: false